
namespace GeniusX.AXA.Underwriting.BusinessLogic
{
    public static class UwMessageConstants
    {
        public const string HEADERSTATUS_VERIFIED_GENIUSUPDATE_NOTALLOWED = "HEADERSTATUS_VERIFIED_GENIUSUPDATE_NOTALLOWED";
        public const string EXTERNALDATASOURCE_REQUIRED = "EXTERNALDATASOURCE_REQUIRED";
        public const string GENIUS_PRODUCT_DOES_NOT_MATCH = "GENIUS_PRODUCT_DOES_NOT_MATCH";
        public const string POLICY_CANNOT_BE_VERIFIED_BY_PERSON_SUBMITTED = "POLICY_CANNOT_BE_VERIFIED_BY_PERSON_SUBMITTED";
        public const string DEDUCTIBLE_SEQUENCE_MUST_BE_GREATER_THAN_ZERO = "DEDUCTIBLE_SEQUENCE_MUST_BE_GREATER_THAN_ZERO";
        public const string DEDUCTIBLE_POLICY_SEQUENCE_SHOULD_BE_ZERO = "DEDUCTIBLE_POLICY_SEQUENCE_SHOULD_BE_ZERO";
        public const string DEDUCTIBLE_POLICY_REFERENCE_SHOULD_NOT_BE_NULL = "DEDUCTIBLE_POLICY_REFERENCE_SHOULD_NOT_BE_NULL"; 
    }
}
