//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeniusX.AXA.FrontendModules.Claims.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeniusX.AXA.FrontendModules.Claims.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AXA Managed Share %%.
        /// </summary>
        public static string AXAManagedShare {
            get {
                return ResourceManager.GetString("AXAManagedShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AXA Share %%.
        /// </summary>
        public static string AXAShare {
            get {
                return ResourceManager.GetString("AXAShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Detail Totals.
        /// </summary>
        public static string ClaimDetailTotals {
            get {
                return ResourceManager.GetString("ClaimDetailTotals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Check.
        /// </summary>
        public static string ClaimSearchTitle {
            get {
                return ResourceManager.GetString("ClaimSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage Verification could not be completed because of the following errors:.
        /// </summary>
        public static string CoverageVerification_WarningAttention {
            get {
                return ResourceManager.GetString("CoverageVerification_WarningAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment Error.
        /// </summary>
        public static string CoverageVerification_WarningTitle {
            get {
                return ResourceManager.GetString("CoverageVerification_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Name Involvement: Major Insured.
        /// </summary>
        public static string Custom_Message_Source_Major_Insured {
            get {
                return ResourceManager.GetString("Custom_Message_Source_Major_Insured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy trigger date {0} is outside cover period ({1} - {2}).
        /// </summary>
        public static string DateOutside_CoverPeriod {
            get {
                return ResourceManager.GetString("DateOutside_CoverPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Reason Code.
        /// </summary>
        public static string DeductibleReasonCodeTitle {
            get {
                return ResourceManager.GetString("DeductibleReasonCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Reason Code.
        /// </summary>
        public static string DeductibleReasonTitle {
            get {
                return ResourceManager.GetString("DeductibleReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string DocumentData_Validation {
            get {
                return ResourceManager.GetString("DocumentData_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are warning messages for your attention. Click Cancel to review them or OK to continue without reviewing..
        /// </summary>
        public static string DocumentData_ValidationWarning {
            get {
                return ResourceManager.GetString("DocumentData_ValidationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalise.
        /// </summary>
        public static string Documents_Menu_Finalise {
            get {
                return ResourceManager.GetString("Documents_Menu_Finalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print &amp; Finalise.
        /// </summary>
        public static string Documents_Menu_PrintAndFinalise {
            get {
                return ResourceManager.GetString("Documents_Menu_PrintAndFinalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Reviewed event created..
        /// </summary>
        public static string Estimation_Event_Created {
            get {
                return ResourceManager.GetString("Estimation_Event_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation Review.
        /// </summary>
        public static string Estimation_Reviewed {
            get {
                return ResourceManager.GetString("Estimation_Reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate Reviewed - No Change.
        /// </summary>
        public static string EstRvwNoChange {
            get {
                return ResourceManager.GetString("EstRvwNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Major_Insured_Title {
            get {
                return ResourceManager.GetString("Major_Insured_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is mandatory.
        /// </summary>
        public static string Mandatory_Field {
            get {
                return ResourceManager.GetString("Mandatory_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The claim is not closed or finalized or there does not exist at least one review task. The current task cannot be completed..
        /// </summary>
        public static string NewClaimTaskCompletionValidationMessage {
            get {
                return ResourceManager.GetString("NewClaimTaskCompletionValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string NewClaimTaskCompletionValidationTitle {
            get {
                return ResourceManager.GetString("NewClaimTaskCompletionValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment {0} / {1} {2} to {3} has been assigned to {4} for authorisation.
        /// </summary>
        public static string Notification_AuthenticationTaskMessage {
            get {
                return ResourceManager.GetString("Notification_AuthenticationTaskMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Authorisation Task.
        /// </summary>
        public static string Notification_AuthenticationTaskTitle {
            get {
                return ResourceManager.GetString("Notification_AuthenticationTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Estimate Reviewed event created.
        /// </summary>
        public static string Recovery_Estimation_Event_Created {
            get {
                return ResourceManager.GetString("Recovery_Estimation_Event_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Estimation Review.
        /// </summary>
        public static string Recovery_Estimation_Review {
            get {
                return ResourceManager.GetString("Recovery_Estimation_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery Estimate Reviewed - No Change.
        /// </summary>
        public static string RecoveryEstRvwNoChange {
            get {
                return ResourceManager.GetString("RecoveryEstRvwNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason.
        /// </summary>
        public static string RejectReasonTitle {
            get {
                return ResourceManager.GetString("RejectReasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litigation/Offers/Recoveries cannot be recorded against an unconfirmed claim..
        /// </summary>
        public static string ReserveLitigation_NotAllowed_On_UnconfirmedClaim {
            get {
                return ResourceManager.GetString("ReserveLitigation_NotAllowed_On_UnconfirmedClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Vehicle.
        /// </summary>
        public static string Resource_ClaimClientRegistrationNumber {
            get {
                return ResourceManager.GetString("Resource_ClaimClientRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Vehicle.
        /// </summary>
        public static string Resource_ClaimTPRegistrationNumber {
            get {
                return ResourceManager.GetString("Resource_ClaimTPRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Reference.
        /// </summary>
        public static string Resource_ClientReference {
            get {
                return ResourceManager.GetString("Resource_ClientReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Resource_Driver {
            get {
                return ResourceManager.GetString("Resource_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outsource Reference.
        /// </summary>
        public static string Resource_OutsourceReference {
            get {
                return ResourceManager.GetString("Resource_OutsourceReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Due Date.
        /// </summary>
        public static string ReviewTaskInitialDueDate {
            get {
                return ResourceManager.GetString("ReviewTaskInitialDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant.
        /// </summary>
        public static string RiskGridHeader_Claimant {
            get {
                return ResourceManager.GetString("RiskGridHeader_Claimant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RiskGridHeader_ClaimHeaderStatusCode {
            get {
                return ResourceManager.GetString("RiskGridHeader_ClaimHeaderStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string RiskGridHeader_ClaimReference {
            get {
                return ResourceManager.GetString("RiskGridHeader_ClaimReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RiskGridHeader_ClaimTitle {
            get {
                return ResourceManager.GetString("RiskGridHeader_ClaimTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Vehicle.
        /// </summary>
        public static string RiskGridHeader_ClientVehicleNumber {
            get {
                return ResourceManager.GetString("RiskGridHeader_ClientVehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string RiskGridHeader_DateOfEventFrom {
            get {
                return ResourceManager.GetString("RiskGridHeader_DateOfEventFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Loss.
        /// </summary>
        public static string RiskGridHeader_DateOfLossFrom {
            get {
                return ResourceManager.GetString("RiskGridHeader_DateOfLossFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string RiskGridHeader_Driver {
            get {
                return ResourceManager.GetString("RiskGridHeader_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured.
        /// </summary>
        public static string RiskGridHeader_Insured {
            get {
                return ResourceManager.GetString("RiskGridHeader_Insured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Reference.
        /// </summary>
        public static string RiskGridHeader_RiskReference {
            get {
                return ResourceManager.GetString("RiskGridHeader_RiskReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Vehicle.
        /// </summary>
        public static string RiskGridHeader_TPVehicleNumber {
            get {
                return ResourceManager.GetString("RiskGridHeader_TPVehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim should only be confirmed if duplicate search results have been checked. Click ‘OK’ to confirm that you have checked for duplicates (this will save the claim), or ‘Cancel’ to review the duplicate check results without saving the claim..
        /// </summary>
        public static string SaveWithWarningDialogText {
            get {
                return ResourceManager.GetString("SaveWithWarningDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string SaveWithWarningDialogTitle {
            get {
                return ResourceManager.GetString("SaveWithWarningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string SearchResultsModel_Claims {
            get {
                return ResourceManager.GetString("SearchResultsModel_Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Shown.
        /// </summary>
        public static string ShareShown {
            get {
                return ResourceManager.GetString("ShareShown", resourceCulture);
            }
        }
    }
}
